target 'NAB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NAB
  pod "StatefulViewController", "~> 3.0"

  target 'NABTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
